var mysql = require('mysql');
var settings = require('../js/settings');

var con = mysql.createConnection({
  host     : settings.dbConfig.host,
  user     : settings.dbConfig.user,
  password : settings.dbConfig.password,
  database:  settings.dbConfig.database
});

con.connect(function(err) {
  if (err) throw err;
  console.log("Connected!");
  //Make SQL statement:
  var sql = "INSERT INTO pais (iso3, nombre, leyenda, iso2) VALUES ?";

  //Make an array of values:
  var values = [
			["ABW", "Aruba", "Aruba", "AW" ],
			["AFG", "Afghanistan", "Afganistan/Afqanestan", "AF" ],
			["AGO", "Angola", "Angola", "AO" ],
			["AIA", "Anguilla", "Anguilla", "AI" ],
			["ALB", "Albania", "Shqipëria", "AL" ],
			["AND", "Andorra", "Andorra", "AD" ],
			["ANT", "Netherlands Antilles", "Nederlandse Antillen", "AN" ],
			["ARE", "United Arab Emirates", "Al-Imarat al-´Arabiya al-Muttahida", "AE" ],
			["ARG", "Argentina", "Argentina", "AR" ],
			["ARM", "Armenia", "Hajastan", "AM" ],
			["ASM", "American Samoa", "Amerika Samoa", "AS" ],
			["ATA", "Antarctica", "Antarctica", "AQ" ],
			["ATF", "French Southern territories", "Terres australes françaises", "TF" ],
			["ATG", "Antigua and Barbuda", "Antigua and Barbuda", "AG" ],
			["AUS", "Australia", "Australia", "AU" ],
			["AUT", "Austria", "Österreich", "AT" ],
			["AZE", "Azerbaijan", "Azärbaycan", "AZ" ],
			["BDI", "Burundi", "Burundi/Uburundi", "BI" ],
			["BEL", "Belgium", "België/Belgique", "BE" ],
			["BEN", "Benin", "Bénin", "BJ" ],
			["BFA", "Burkina Faso", "Burkina Faso", "BF" ],
			["BGD", "Bangladesh", "Bangladesh", "BD" ],
			["BGR", "Bulgaria", "Balgarija", "BG" ],
			["BHR", "Bahrain", "Al-Bahrayn", "BH" ],
			["BHS", "Bahamas", "The Bahamas", "BS" ],
			["BIH", "Bosnia and Herzegovina", "Bosna i Hercegovina", "BA" ],
			["BLR", "Belarus", "Belarus", "BY" ],
			["BLZ", "Belize", "Belize", "BZ" ],
			["BMU", "Bermuda", "Bermuda", "BM" ],
			["BOL", "Bolivia", "Bolivia", "BO" ],
			["BRA", "Brazil", "Brasil", "BR" ],
			["BRB", "Barbados", "Barbados", "BB" ],
			["BRN", "Brunei", "Brunei Darussalam", "BN" ],
			["BTN", "Bhutan", "Druk-Yul", "BT" ],
			["BVT", "Bouvet Island", "Bouvetøya", "BV" ],
			["BWA", "Botswana", "Botswana", "BW" ],
			["CAF", "Central African Republic", "Centrafrique/Bê-Afrîka", "CF" ],
			["CAN", "Canada", "Canada", "CA" ],
			["CCK", "Cocos (Keeling) Islands", "Cocos (Keeling) Islands", "CC" ],
			["CHE", "Switzerland", "Schweiz/Suisse/Svizzera/Svizra", "CH" ],
			["CHL", "Chile", "Chile", "CL" ],
			["CHN", "China", "Zhongquo", "CN" ],
			["CIV", "Côte d’Ivoire", "Côte d’Ivoire", "CI" ],
			["CMR", "Cameroon", "Cameroun/Cameroon", "CM" ],
			["COD", "Cong", "République Démocratique du Congo", "CD" ],
			["COG", "Congo", "Congo", "CG" ],
			["COK", "Cook Islands", "The Cook Islands", "CK" ],
			["COL", "Colombia", "Colombia", "CO" ],
			["COM", "Comoros", "Komori/Comores", "KM" ],
			["CPV", "Cape Verde", "Cabo Verde", "CV" ],
			["CRI", "Costa Rica", "Costa Rica", "CR" ],
			["CUB", "Cuba", "Cuba", "CU" ],
			["CXR", "Christmas Island", "Christmas Island", "CX" ],
			["CYM", "Cayman Islands", "Cayman Islands", "KY" ],
			["CYP", "Cyprus", "Kýpros/Kibris", "CY" ],
			["CZE", "Czech Republic", "¸esko", "CZ" ],
			["DEU", "Germany", "Deutschland", "DE" ],
			["DJI", "Djibouti", "Djibouti/Jibuti", "DJ" ],
			["DMA", "Dominica", "Dominica", "DM" ],
			["DNK", "Denmark", "Danmark", "DK" ],
			["DOM", "Dominican Republic", "República Dominicana", "DO" ],
			["DZA", "Algeria", "Al-Jaza’ir/Algérie", "DZ" ],
			["ECU", "Ecuador", "Ecuador", "EC" ],
			["EGY", "Egypt", "Misr", "EG" ],
			["ERI", "Eritrea", "Ertra", "ER" ],
			["ESH", "Western Sahara", "As-Sahrawiya", "EH" ],
			["ESP", "Spain", "España", "ES" ],
			["EST", "Estonia", "Eesti", "EE" ],
			["ETH", "Ethiopia", "YeItyop´iya", "ET" ],
			["FIN", "Finland", "Suomi", "FI" ],
			["FJI", "Fiji Islands", "Fiji Islands", "FJ" ],
			["FLK", "Falkland Islands", "Falkland Islands", "FK" ],
			["FRA", "France", "France", "FR" ],
			["FRO", "Faroe Islands", "Føroyar", "FO" ],
			["FSM", "Micronesi", "Federal Republic", "FM" ],
			["GAB", "Gabon", "Le Gabon", "GA" ],
			["GBR", "United Kingdom", "United Kingdom", "GB" ],
			["GEO", "Georgia", "Sakartvelo", "GE" ],
			["GHA", "Ghana", "Ghana", "GH" ],
			["GIB", "Gibraltar", "Gibraltar", "GI" ],
			["GIN", "Guinea", "Guinée", "GN" ],
			["GLP", "Guadeloupe", "Guadeloupe", "GP" ],
			["GMB", "Gambia", "The Gambia", "GM" ],
			["GNB", "Guinea-Bissau", "Guiné-Bissau", "GW" ],
			["GNQ", "Equatorial Guinea", "Guinea Ecuatorial", "GQ" ],
			["GRC", "Greece", "Elláda", "GR" ],
			["GRD", "Grenada", "Grenada", "GD" ],
			["GRL", "Greenland", "Kalaallit Nunaat/Grønland", "GL" ],
			["GTM", "Guatemala", "Guatemala", "GT" ],
			["GUF", "French Guiana", "Guyane française", "GF" ],
			["GUM", "Guam", "Guam", "GU" ],
			["GUY", "Guyana", "Guyana", "GY" ],
			["HKG", "Hong Kong", "Xianggang/Hong Kong", "HK" ],
			["HMD", "Heard Island and McDonald Islands", "Heard and McDonald Islands", "HM" ],
			["HND", "Honduras", "Honduras", "HN" ],
			["HRV", "Croatia", "Hrvatska", "HR" ],
			["HTI", "Haiti", "Haïti/Dayti", "HT" ],
			["HUN", "Hungary", "Magyarország", "HU" ],
			["IDN", "Indonesia", "Indonesia", "ID" ],
			["IND", "India", "Bharat/India", "IN" ],
			["IOT", "British Indian Ocean Territory", "British Indian Ocean Territory", "IO" ],
			["IRL", "Ireland", "Ireland/Éire", "IE" ],
			["IRN", "Iran", "Iran", "IR" ],
			["IRQ", "Iraq", "Al-´Iraq", "IQ" ],
			["ISL", "Iceland", "Ísland", "IS" ],
			["ISR", "Israel", "Yisra’el/Isra’il", "IL" ],
			["ITA", "Italy", "Italia", "IT" ],
			["JAM", "Jamaica", "Jamaica", "JM" ],
			["JOR", "Jordan", "Al-Urdunn", "JO" ],
			["JPN", "Japan", "Nihon/Nippon", "JP" ],
			["KAZ", "Kazakstan", "Qazaqstan", "KZ" ],
			["KEN", "Kenya", "Kenya", "KE" ],
			["KGZ", "Kyrgyzstan", "Kyrgyzstan", "KG" ],
			["KHM", "Cambodia", "Kâmpuchéa", "KH" ],
			["KIR", "Kiribati", "Kiribati", "KI" ],
			["KNA", "Saint Kitts and Nevis", "Saint Kitts and Nevis", "KN" ],
			["KOR", "South Korea", "Taehan Min’guk (Namhan)", "KR" ],
			["KWT", "Kuwait", "Al-Kuwayt", "KW" ],
			["LAO", "Laos", "Lao", "LA" ],
			["LBN", "Lebanon", "Lubnan", "LB" ],
			["LBR", "Liberia", "Liberia", "LR" ],
			["LBY", "Libyan Arab Jamahiriya", "Libiya", "LY" ],
			["LCA", "Saint Lucia", "Saint Lucia", "LC" ],
			["LIE", "Liechtenstein", "Liechtenstein", "LI" ],
			["LKA", "Sri Lanka", "Sri Lanka/Ilankai", "LK" ],
			["LSO", "Lesotho", "Lesotho", "LS" ],
			["LTU", "Lithuania", "Lietuva", "LT" ],
			["LUX", "Luxembourg", "Luxembourg/Lëtzebuerg", "LU" ],
			["LVA", "Latvia", "Latvija", "LV" ],
			["MAC", "Macao", "Macau/Aomen", "MO" ],
			["MAR", "Morocco", "Al-Maghrib", "MA" ],
			["MCO", "Monaco", "Monaco", "MC" ],
			["MDA", "Moldova", "Moldova", "MD" ],
			["MDG", "Madagascar", "Madagasikara/Madagascar", "MG" ],
			["MDV", "Maldives", "Dhivehi Raajje/Maldives", "MV" ],
			["MEX", "Mexico", "México", "MX" ],
			["MHL", "Marshall Islands", "Marshall Islands/Majol", "MH" ],
			["MKD", "Macedonia", "Makedonija", "MK" ],
			["MLI", "Mali", "Mali", "ML" ],
			["MLT", "Malta", "Malta", "MT" ],
			["MMR", "Myanmar", "Myanma Pye", "MM" ],
			["MNG", "Mongolia", "Mongol Uls", "MN" ],
			["MNP", "Northern Mariana Islands", "Northern Mariana Islands", "MP" ],
			["MOZ", "Mozambique", "Moçambique", "MZ" ],
			["MRT", "Mauritania", "Muritaniya/Mauritanie", "MR" ],
			["MSR", "Montserrat", "Montserrat", "MS" ],
			["MTQ", "Martinique", "Martinique", "MQ" ],
			["MUS", "Mauritius", "Mauritius", "MU" ],
			["MWI", "Malawi", "Malawi", "MW" ],
			["MYS", "Malaysia", "Malaysia", "MY" ],
			["MYT", "Mayotte", "Mayotte", "YT" ],
			["NAM", "Namibia", "Namibia", "NA" ],
			["NCL", "New Caledonia", "Nouvelle-Calédonie", "NC" ],
			["NER", "Niger", "Niger", "NE" ],
			["NFK", "Norfolk Island", "Norfolk Island", "NF" ],
			["NGA", "Nigeria", "Nigeria", "NG" ],
			["NIC", "Nicaragua", "Nicaragua", "NI" ],
			["NIU", "Niue", "Niue", "NU" ],
			["NLD", "Netherlands", "Nederland", "NL" ],
			["NOR", "Norway", "Norge", "NO" ],
			["NPL", "Nepal", "Nepal", "NP" ],
			["NRU", "Nauru", "Naoero/Nauru", "NR" ],
			["NZL", "New Zealand", "New Zealand/Aotearoa", "NZ" ],
			["OMN", "Oman", "´Uman", "OM" ],
			["PAK", "Pakistan", "Pakistan", "PK" ],
			["PAN", "Panama", "Panamá", "PA" ],
			["PCN", "Pitcairn", "Pitcairn", "PN" ],
			["PER", "Peru", "Perú/Piruw", "PE" ],
			["PHL", "Philippines", "Pilipinas", "PH" ],
			["PLW", "Palau", "Belau/Palau", "PW" ],
			["PNG", "Papua New Guinea", "Papua New Guinea/Papua Niugini", "PG" ],
			["POL", "Poland", "Polska", "PL" ],
			["PRI", "Puerto Rico", "Puerto Rico", "PR" ],
			["PRK", "North Korea", "Choson Minjujuui In´min Konghwaguk (Bukhan)", "KP" ],
			["PRT", "Portugal", "Portugal", "PT" ],
			["PRY", "Paraguay", "Paraguay", "PY" ],
			["PSE", "Palestine", "Filastin", "PS" ],
			["PYF", "French Polynesia", "Polynésie française", "PF" ],
			["QAT", "Qatar", "Qatar", "QA" ],
			["REU", "Réunion", "Réunion", "RE" ],
			["ROM", "Romania", "România", "RO" ],
			["RUS", "Russian Federation", "Rossija", "RU" ],
			["RWA", "Rwanda", "Rwanda/Urwanda", "RW" ],
			["SAU", "Saudi Arabia", "Al-´Arabiya as-Sa´udiya", "SA" ],
			["SDN", "Sudan", "As-Sudan", "SD" ],
			["SEN", "Senegal", "Sénégal/Sounougal", "SN" ],
			["SGP", "Singapore", "Singapore/Singapura/Xinjiapo/Singapur", "SG" ],
			["SGS", "South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands", "GS" ],
			["SHN", "Saint Helena", "Saint Helena", "SH" ],
			["SJM", "Svalbard and Jan Mayen", "Svalbard og Jan Mayen", "SJ" ],
			["SLB", "Solomon Islands", "Solomon Islands", "SB" ],
			["SLE", "Sierra Leone", "Sierra Leone", "SL" ],
			["SLV", "El Salvador", "El Salvador", "SV" ],
			["SMR", "San Marino", "San Marino", "SM" ],
			["SOM", "Somalia", "Soomaaliya", "SO" ],
			["SPM", "Saint Pierre and Miquelon", "Saint-Pierre-et-Miquelon", "PM" ],
			["STP", "Sao Tome and Principe", "São Tomé e Príncipe", "ST" ],
			["SUR", "Suriname", "Suriname", "SR" ],
			["SVK", "Slovakia", "Slovensko", "SK" ],
			["SVN", "Slovenia", "Slovenija", "SI" ],
			["SWE", "Sweden", "Sverige", "SE" ],
			["SWZ", "Swaziland", "kaNgwane", "SZ" ],
			["SYC", "Seychelles", "Sesel/Seychelles", "SC" ],
			["SYR", "Syria", "Suriya", "SY" ],
			["TCA", "Turks and Caicos Islands", "The Turks and Caicos Islands", "TC" ],
			["TCD", "Chad", "Tchad/Tshad", "TD" ],
			["TGO", "Togo", "Togo", "TG" ],
			["THA", "Thailand", "Prathet Thai", "TH" ],
			["TJK", "Tajikistan", "Toçikiston", "TJ" ],
			["TKL", "Tokelau", "Tokelau", "TK" ],
			["TKM", "Turkmenistan", "Türkmenostan", "TM" ],
			["TMP", "East Timor", "Timor Timur", "TP" ],
			["TON", "Tonga", "Tonga", "TO" ],
			["TTO", "Trinidad and Tobago", "Trinidad and Tobago", "TT" ],
			["TUN", "Tunisia", "Tunis/Tunisie", "TN" ],
			["TUR", "Turkey", "Türkiye", "TR" ],
			["TUV", "Tuvalu", "Tuvalu", "TV" ],
			["TWN", "Taiwan", "T’ai-wan", "TW" ],
			["TZA", "Tanzania", "Tanzania", "TZ" ],
			["UGA", "Uganda", "Uganda", "UG" ],
			["UKR", "Ukraine", "Ukrajina", "UA" ],
			["UMI", "United States Minor Outlying Islands", "United States Minor Outlying Islands", "UM" ],
			["URY", "Uruguay", "Uruguay", "UY" ],
			["USA", "United States", "United States", "US" ],
			["UZB", "Uzbekistan", "Uzbekiston", "UZ" ],
			["VAT", "Holy See (Vatican City State)", "Santa Sede/Città del Vaticano", "VA" ],
			["VCT", "Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines", "VC" ],
			["VEN", "Venezuela", "Venezuela", "VE" ],
			["VGB", "Virgin Island", "British Virgin Islands", "VG" ],
			["VIR", "Virgin Island", "Virgin Islands of the United States", "VI" ],
			["VNM", "Vietnam", "Viêt Nam", "VN" ],
			["VUT", "Vanuatu", "Vanuatu", "VU" ],
			["WLF", "Wallis and Futuna", "Wallis-et-Futuna", "WF" ],
			["WSM", "Samoa", "Samoa", "WS" ],
			["YEM", "Yemen", "Al-Yaman", "YE" ],
			["YUG", "Yugoslavia", "Jugoslavija", "YU" ],
			["ZAF", "South Africa", "South Africa", "ZA" ],
			["ZMB", "Zambia", "Zambia", "ZM" ],
			["ZWE", "Zimbabwe", "Zimbabwe", "ZW" ]
  ];
  //Execute the SQL statement, with the value array:
  con.query(sql, [values], function (err, result) {
    if (err) throw err;
    console.log("Number of records inserted: " + result.affectedRows);
  });
});
